backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  
media_folder: "_site/assets/post_img"
public_folder: "assets/post_img"

collections:
  - name: "Post"
    label: "Blog Posting"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author(heomne)", name: author, widget: "string", default: "heomne"}
      - {label: "Publicsh Date", name: "date", }
      - {label: "Tag", name: "tags", widget: "string"}
      - {label: "Category", name: "categories", widget: "string"}
      - {label: "Thumbnail(Optional)", name: "img_path", widget: "image"}
      - {label: "pin", name: "pin", widget: "required"}