backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "/assets/post_img"
public_folder: "/_site/assets/post_img"
site_url: https://heomne.github.io
display_url: https://heomne.github.io
logo_url: https://avatars.githubusercontent.com/u/79975278?s=400&u=f138cb908e12521218253da0b18d5e95a4197919&v=4

collections:
  - name: "Post"
    label: "Blog Posting"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Author(heomne)",
          name: author,
          widget: "string",
          default: "heomne"
        }
      - { label: "Publicsh Date", name: "date" }
      - { label: "Tag", name: "tags", widget: "string" }
      - { label: "Category", name: "categories", widget: "string" }
      - {
          label: "Thumbnail",
          name: "img_path",
          widget: "image",
          required: false
        }
      - { label: "pin", name: "pin", widget: "boolean" }
      - { label: "Content", name: "body", widget: "markdown" }
